# Generated by Django 2.2.6 on 2019-10-03 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='indicators',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.IntegerField()),
                ('heartRate', models.CharField(max_length=20)),
                ('systolicBloodPressure', models.CharField(max_length=20)),
                ('diastolicBloodPressure', models.CharField(max_length=20)),
                ('bloodOxygenation', models.CharField(max_length=20)),
                ('createDate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roleId', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=20)),
                ('gender', models.BooleanField()),
                ('age', models.IntegerField()),
                ('description', models.CharField(max_length=200)),
                ('roleId', models.IntegerField()),
            ],
        ),
    ]
