# Generated by Django 2.2.6 on 2019-10-04 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0003_auto_20191004_0116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicators',
            name='createDate',
            field=models.DateField(),
        ),
    ]
