# Generated by Django 2.2.6 on 2019-10-04 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0005_auto_20191004_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicators',
            name='bloodOxygenation',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='indicators',
            name='diastolicBloodPressure',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='indicators',
            name='heartRate',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='indicators',
            name='systolicBloodPressure',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='indicators',
            name='userId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', to='medical.user'),
        ),
    ]
