# Generated by Django 2.2.6 on 2019-10-04 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0006_auto_20191004_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='roleId',
            field=models.IntegerField(null=True),
        ),
    ]
